klaritywiki/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('wiki.urls')),
]

wiki/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse
from . import views

app_name = 'wiki'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="detail"),
    url(r'^categories/(?P<pk>[0-9]+)/edit/$', views.AlbumUpdate.as_view(), name='edit_category'),
    # url(r'^(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
]

wiki/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse


class Website(models.Model):
    website_name = models.CharField(max_length=200)
    website_url = models.CharField(max_length=1000)
    website_cms = models.CharField(max_length=100)

    def __str__(self):
        return self.website_name


class Categories(models.Model):
    website_name = models.ForeignKey(Website, on_delete=models.CASCADE)
    title = models.CharField(max_length=500)
    author = models.ForeignKey('auth.User')
    text = models.TextField(blank = True, null = True)
    published_date = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('wiki:detail', kwargs={'pk': self.pk})

    def publish(self):
        self.published_date -timezone.now()
        self.save()

    def __str__(self):
        return self.title

wiki/views.py
from .models import Website, Categories
from django.views import generic

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View


# Create your views here.


class IndexView(generic.ListView):
    template_name = 'wiki/index.html'
    context_object_name = 'website_list'

    def get_queryset(self):
        return Website.objects.all()

class DetailView(generic.DetailView):
    model = Categories
    template_name = 'wiki/detail.html'

class AlbumUpdate(UpdateView):
    model = Categories
    fields =['title','text']

wiki/templates/wiki/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Klarity Wiki{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'wiki/css/styles.css'%}">
  </head>
  <body>
    <header>
      <nav>
        <div class="nav-container">
          <div class="logo">
              <a href="{% url 'wiki:index' %}"><img src="#" alt="Klarity logo" /></a>
          </div>
          <ul>
            <li><a href="#">Add a Website</a></li>
            <li>
              <form class="search" action="" method="get">
                <input type="text" name="name" value="">
                <input type="submit" name="name" value="submit">
              </form>
            </li>
            <li><a href="#">Add a Category</a></li>
            {% if user.is_authenticated %}
            <li><a href="/admin/logout">Logout</a></li>
            {% else %}
            <li><a href="/admin/">Login</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    {% block body%}
    {% endblock %}
    <footer></footer>
  </body>
</html>

wiki/templates/wiki/categories_form.html
<!-- this file needs to be the name of the model + _form-->

{% extends 'wiki/base.html' %}
{% load staticfiles %}
{% block title %}Add new album{% endblock %}
{% block body %}

    <div class="container-fluid">
        <div class="col-sm-12 col-md-7 ">
            <div class="panel panel-default">
                <dv class="panel-body">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'wiki/includes/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn">Submit</button>
                            </div>
                        </div>
                    </form>
                </dv>
            </div>
        </div>
    </div>

{% endblock %}

wiki/templates/wiki/detail.html
{% extends 'wiki/base.html' %}
{% load staticfiles %}
{% block title %}Wiki details{% endblock %}
{% block body %}

    <a href="{% url 'wiki:index' %}">Go back</a>

    <section>

        <h1>{{categories.title}}</h1>
        <h3>Author:{{categories.author}}</h3>
        <h5>{{categories.published_date}}</h5>
        {% if user.is_authenticated %}
        <a href="{% url 'wiki:edit_category' categories.id %}">edit</a>
        {% endif %}
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <div class="content">
          {{categories.text |safe|linebreaksbr}}
        </div>

        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
    </section>
{% endblock %}

wiki/templates/wiki/forms.html
{% extends 'wiki/base.html' %}
{% block content %}
<form method="POST" >
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit</button>
</form>

{% endblock  %}

wiki/templates/wiki/includes/form-template.html
{% for field in form %}
    <div class="form-group">
       <div class="error-message">
           <span>{{field.errors}}</span>
       </div>
        <label>{{field.label_tag}}</label>
        <div class="input">{{field}}</div>
    </div>
{% endfor %}

wiki/templates/wiki/index.html
{% extends 'wiki/base.html' %}

{% block body %}
<ul>
  {% for web in website_list %}
  <li><a href="{% url 'wiki:detail' web.id %}">{{web.website_name}}</a></li>
  {% endfor %}
</ul>
{% endblock %}